export const data = [
    {
        header: "Munda Women (India) and Health Care",
        subHeader: "Munda-Frauen (Indien) und Gesundheitsversorgung",
        author: "Peter Paul Hembrom",
        detailsOne: "Abstract :- Horopathy Ethnomedicine is the medicine of the MUNDA ethnic Group of India, Where social medical is the culture and self medication is the practice. Taking advantage of this, if women, who are mothers, nurses and care takers of the family are trained in the scientific medicinal use of locally available berbs around their villages and on cultivable land (as they are from agricultural communities) they can take care of their primary health , as well as on that of their family, while children can make it sustained . Women would then command respect in the society.",
        detailsSecond:"Zusammenfassung : - Horopathic mennt sich die Medizin der ethnischen Gruppe der Munda in Indien, bei denen siziale Medizin die kultur und selbstbehandlung die Praxis darstellt. Davon konnen die Frauen profitieren: wenn sie ,die zuglecih Mutter, Krankenpflegerinnen und Betreuerinnen derFamilie sind , in der korrekten medizinischen Anwendung der in der umgebung ihrer Dorfer und auf kultivierbarem Land (sofern sie in bauerlichen agrarischen Gemeinden leben)verfunbaren Heilkrauter geschult warden, konnen sie die eigene gesundheitlichen Grundversorgung wie auch die ihrer Familie sichern,wahrend die Kinder sie bewahren lernen konnen. Auf diese Weise gewinnen die Frauen-Grundversorgung wie auch die ihrer Familie sichern, wahrend die Kinder sie bewahren lernen konnen. Auf diese Weise gewinnen die Frauen den Respekt der Gesellschaft.",
        detailsThree : "Keywords :- India, Munda-women, horopathy ethnomedicine, health of women,training of women,respect, Indien, Munda-Frauen, horopathy Ethnomedizin, Frauen-Gesundheit, Ausidung von Frauen, Respekt. There are about million people belonging to tribes in india. On a linguistic basis there are communities with 705 ethnic groups. The munda speech of Central Eastern India, Nicobarese and Santhals have been placed in Australic Asiatic linguistic branch.About 7500 wild plant soecies are currently recorded as being used by Mundas for medicine."
    }
]